/* Fabric.js professional canvas adapter. The application state remains the source of truth. */
let fabricLayoutCanvas=null,fabricSyncing=false;
function fabricTypeCounts(items){const layers=new Map((model().layoutDocument?.layers||[]).map(l=>[l.id,l])),visible=items.filter(o=>o.visible!==false&&layers.get(o.layerId)?.visible!==false),count=types=>visible.filter(o=>types.includes(o.type)).length;return{leader:count(['worker-leader']),support:count(['worker-support']),qc:count(['worker-pink']),skill:count(['star']),workers:count(['worker','worker-pink','worker-leader','worker-support']),process:count(['process-station']),tables:count(['table','station']),machine:count(['laser','machine-frame','machine','equipment','auto','vinyl','vision']),jig:count(['jig-attach','jig-cclip','jig-dino','tester-dmc','tester-wlt','tester-vswr']),press:count(['jig-v0','jig-v3'])}}
renderShapeSummary=function(items){const n=fabricTypeCounts(items);$('shapeLeaderCount').textContent=n.leader;$('shapeSupportCount').textContent=n.support;$('shapeQcCount').textContent=n.qc;$('shapeSkillCount').textContent=n.skill;$('shapeWorkerCount').textContent=n.workers;$('shapeProcessCount').textContent=n.process;$('shapeMachineCount').textContent=n.machine;$('shapeJigCount').textContent=n.jig;$('shapePressCount').textContent=n.press};
function fabricLabel(o){return String(o.text||'').trim()}
function fabricWorker(o,color='#00aeef'){const fill=o.fillColor&&o.fillColor!=='none'?o.fillColor:color,w=Math.max(32,o.width),h=Math.max(44,o.height),stroke=o.strokeColor&&o.strokeColor!=='none'?o.strokeColor:fill,line=Math.max(3,Math.min(w,h)*.1),cx=w/2,head=new fabric.Circle({left:cx-h*.11,top:h*.06,radius:h*.11,fill}),body=new fabric.Rect({left:cx-h*.075,top:h*.31,width:h*.15,height:h*.31,rx:line,ry:line,fill}),arms=new fabric.Line([w*.14,h*.42,w*.86,h*.42],{stroke,strokeWidth:line,strokeLineCap:'round'}),legA=new fabric.Line([cx-h*.055,h*.62,w*.27,h*.92],{stroke,strokeWidth:line,strokeLineCap:'round'}),legB=new fabric.Line([cx+h*.055,h*.62,w*.73,h*.92],{stroke,strokeWidth:line,strokeLineCap:'round'});return new fabric.Group([head,body,arms,legA,legB],{left:o.x,top:o.y,angle:o.rotation||0,objectCaching:false})}
function fabricTable(o,common){const fill=o.fillColor&&o.fillColor!=='none'?o.fillColor:'#1f6687',stroke=o.strokeColor&&o.strokeColor!=='none'?o.strokeColor:'#0c415b',rect=new fabric.Rect({width:o.width,height:o.height,fill,stroke,strokeWidth:Math.max(2,+o.strokeWidth||3)}),label=fabricLabel(o);const members=[rect];if(label&&!/^(table|work table|bàn)$/i.test(label))members.push(new fabric.Textbox(label,{left:6,top:Math.max(4,o.height/2-12),width:Math.max(20,o.width-12),fontSize:o.style?.fontSize||Math.min(16,Math.max(10,o.height/4)),fontWeight:o.style?.fontWeight||'bold',textAlign:'center',fill:o.style?.textColor||'#fff',selectable:false,evented:false}));return new fabric.Group(members,{...common,fill:undefined,stroke:undefined,width:o.width,height:o.height})}
function fabricObject(o){const editable=canEdit(),inspectable=!editable&&matchMedia('(max-width: 768px), (max-height: 500px) and (max-width: 950px)').matches,common={left:o.x,top:o.y,angle:o.rotation||0,fill:o.fillColor==='none'?'transparent':o.fillColor||'#fff',stroke:o.strokeColor==='none'?'transparent':o.strokeColor||'#334',strokeWidth:+o.strokeWidth||2,opacity:o.style?.opacity==null?1:+o.style.opacity,objectCaching:false,selectable:editable,evented:editable||inspectable,hasControls:editable,transparentCorners:false,cornerColor:'#fff',cornerStrokeColor:'#0f766e',borderColor:'#0f766e',cornerSize:11,padding:2};let obj;
 if(o.type==='polyline'||o.type==='polygon')obj=new fabric.Polyline(o.points||[],{...common,fill:o.type==='polygon'?common.fill:'transparent'});
 else if(o.type==='dimension-h'||o.type==='dimension-v'){const horizontal=o.type==='dimension-h',len=horizontal?o.width:o.height,line=new fabric.Line(horizontal?[0,o.height/2,o.width,o.height/2]:[o.width/2,0,o.width/2,o.height],{stroke:common.stroke,strokeWidth:2}),a=new fabric.Triangle({width:10,height:10,fill:common.stroke,left:horizontal?0:o.width/2,top:horizontal?o.height/2:0,angle:horizontal?90:180,originX:'center',originY:'center'}),b=new fabric.Triangle({width:10,height:10,fill:common.stroke,left:horizontal?o.width:o.width/2,top:horizontal?o.height/2:o.height,angle:horizontal?270:0,originX:'center',originY:'center'}),label=new fabric.Textbox(fabricLabel(o),{left:horizontal?10:o.width/2+8,top:horizontal?0:o.height/2-10,width:horizontal?o.width-20:70,fontSize:12,fill:'#17343f',backgroundColor:'#fff',textAlign:'center'});obj=new fabric.Group([line,a,b,label],{left:o.x,top:o.y,angle:o.rotation||0})}
 else if(o.type==='fabric-path')obj=new fabric.Path(o.path||[],{...common,fill:'transparent'});
 else if(['worker','worker-pink','worker-leader','worker-support'].includes(o.type))obj=fabricWorker(o,o.type==='worker'?'#10b9de':o.type==='worker-pink'?'#d979c5':o.type==='worker-leader'?'#9b59b6':'#43a047');
 else if(o.type==='table')obj=fabricTable(o,common);
 else if(o.type==='circle')obj=new fabric.Ellipse({...common,rx:o.width/2,ry:o.height/2});
 else if(o.type==='triangle')obj=new fabric.Triangle({...common,width:o.width,height:o.height});
 else if(o.type==='line')obj=new fabric.Line([0,o.height/2,o.width,o.height/2],{...common,fill:null});
 else if(o.type==='arrow'||o.type==='block-arrow')obj=new fabric.Path(`M 0 ${o.height*.3} L ${o.width*.65} ${o.height*.3} L ${o.width*.65} 0 L ${o.width} ${o.height/2} L ${o.width*.65} ${o.height} L ${o.width*.65} ${o.height*.7} L 0 ${o.height*.7} Z`,{...common});
 else if(o.type==='star')obj=new fabric.Polygon(Array.from({length:10},(_,i)=>{const a=-Math.PI/2+i*Math.PI/5,r=i%2?o.width*.22:o.width*.48;return{x:o.width/2+Math.cos(a)*r,y:o.height/2+Math.sin(a)*r}}),{...common});
 else if(o.type==='text')obj=new fabric.IText(fabricLabel(o)||'Văn bản',{...common,fontSize:o.style?.fontSize||18,fontFamily:o.style?.fontFamily||'Arial',fontWeight:o.style?.fontWeight||'normal',fontStyle:o.style?.fontStyle||'normal',underline:!!o.style?.underline,textAlign:o.style?.textAlign||'left',fill:o.style?.textColor||common.fill,width:o.width});
 else {const radius=Math.max(0,Number(o.style?.borderRadius??(o.type==='rounded-rectangle'?10:0))||0),rect=new fabric.Rect({width:o.width,height:o.height,rx:radius,ry:radius,fill:common.fill,stroke:common.stroke,strokeWidth:common.strokeWidth,strokeDashArray:o.style?.strokeDashArray||null});const label=new fabric.Textbox(fabricLabel(o),{left:6,top:Math.max(4,o.height/2-15),width:Math.max(20,o.width-12),fontSize:o.style?.fontSize||Math.min(16,Math.max(10,o.height/4)),fontWeight:o.style?.fontWeight||'bold',fontStyle:o.style?.fontStyle||'normal',underline:!!o.style?.underline,fontFamily:o.style?.fontFamily||'Arial',textAlign:o.style?.textAlign||'center',fill:o.style?.textColor||'#17343f',selectable:false,evented:false});obj=new fabric.Group([rect,label],{...common,fill:undefined,stroke:undefined,width:o.width,height:o.height})}
 obj.layoutId=o.id;obj.layoutType=o.type;obj.layoutText=o.text||'';obj.lockMovementX=!editable||!!o.locked;obj.lockMovementY=!editable||!!o.locked;obj.lockScalingX=!editable||!!o.locked;obj.lockScalingY=!editable||!!o.locked;obj.lockRotation=!editable||!!o.locked;obj.setControlsVisibility({mt:editable,mb:editable,ml:editable,mr:editable,tl:editable,tr:editable,bl:editable,br:editable,mtr:editable});return obj}
function syncFabricObject(obj){if(fabricSyncing||!canEdit()||!obj?.layoutId)return;const row=shapeArray().find(o=>o.id===obj.layoutId);if(!row)return;const old={x:row.x,y:row.y,width:row.width,height:row.height,rotation:row.rotation};row.x=Math.max(0,Math.round(obj.left));row.y=Math.max(0,Math.round(obj.top));row.width=Math.max(8,Math.round(obj.getScaledWidth()));row.height=Math.max(8,Math.round(obj.getScaledHeight()));row.rotation=Math.round(obj.angle||0);recordAudit('Chỉnh sửa đối tượng Fabric.js',row.text||row.type,old,{x:row.x,y:row.y,width:row.width,height:row.height,rotation:row.rotation});persistLocal();scheduleSave();renderShapeSummary(shapeArray())}
function editFabricText(obj){if(!canEdit()||obj.lockMovementX)return;const row=shapeArray().find(o=>o.id===obj.layoutId);if(!row)return;if(obj.type==='i-text'){obj.enterEditing();obj.selectAll();return}const host=$('equipmentDiagram'),box=host.getBoundingClientRect(),input=document.createElement('textarea');input.className='fabric-inline-editor';input.value=row.text||'';input.style.left=(obj.left*shapeZoom-host.parentElement.scrollLeft)+'px';input.style.top=(obj.top*shapeZoom-host.parentElement.scrollTop)+'px';input.style.width=Math.max(150,obj.getScaledWidth()*shapeZoom)+'px';host.appendChild(input);const finish=save=>{if(save){row.text=input.value.trim()||row.text;recordAudit('Sửa chữ trên Fabric.js',row.type,null,row.text);persistLocal();scheduleSave()}input.remove();renderShapesCanvas()};input.onkeydown=e=>{if(e.key==='Escape')finish(false);else if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();finish(true)}};input.onblur=()=>finish(true);setTimeout(()=>{input.focus();input.select()},0)}
renderShapesCanvas=function(){if(!$('equipmentDiagram')||!window.fabric)return;ensureShapeObjects();const items=shapeArray(),scroll=document.querySelector('.shapes-canvas-scroll'),sx=scroll?.scrollLeft||0,sy=scroll?.scrollTop||0;renderShapeSummary(items);$('shapeObjectCount').textContent=`${items.length} đối tượng · Fabric.js`;
 if(fabricLayoutCanvas){fabricLayoutCanvas.dispose();fabricLayoutCanvas=null}$('equipmentDiagram').innerHTML='<canvas id="fabricLayoutSurface"></canvas>';const worldSize=model().layoutDocument?.canvas||SHAPE_CANVAS,officeHost=document.querySelector('.pro-canvas-host'),viewportWidth=Math.max(720,(officeHost?.clientWidth||1000)-84),viewportHeight=Math.max(520,Math.min(760,(officeHost?.clientHeight||650)-40));$('equipmentDiagram').style.width=viewportWidth+'px';$('equipmentDiagram').style.height=viewportHeight+'px';const world=model().layoutDocument?.canvas||SHAPE_CANVAS;fabricLayoutCanvas=new fabric.Canvas('fabricLayoutSurface',{width:viewportWidth,height:viewportHeight,selection:canEdit(),preserveObjectStacking:true,backgroundColor:'#fbfdfc',fireRightClick:true,stopContextMenu:true});fabricLayoutCanvas.setZoom(shapeZoom);fabricSyncing=true;items.forEach(o=>fabricLayoutCanvas.add(fabricObject(o)));fabricSyncing=false;fabricLayoutCanvas.on('object:moving',e=>{const canvas=model().layoutDocument?.canvas;if(!canvas?.snapGrid)return;const g=Math.max(1,(canvas.gridMeters||.5)*(canvas.pixelsPerMeter||60));e.target.set({left:Math.round(e.target.left/g)*g,top:Math.round(e.target.top/g)*g})});fabricLayoutCanvas.on('object:modified',e=>syncFabricObject(e.target));fabricLayoutCanvas.on('text:changed',e=>{const row=shapeArray().find(o=>o.id===e.target.layoutId);if(row){row.text=e.target.text;persistLocal();scheduleSave()}});fabricLayoutCanvas.on('path:created',e=>{if(fabricSyncing||!canEdit())return;const p=e.path,row={id:'shape-'+Date.now(),type:'fabric-path',path:p.path,x:p.left,y:p.top,width:p.width,height:p.height,text:'Nét vẽ',fillColor:'none',strokeColor:p.stroke||'#0f766e',strokeWidth:p.strokeWidth||2,rotation:p.angle||0};p.layoutId=row.id;p.layoutType=row.type;shapeArray().push(row);recordAudit('Vẽ nét Fabric.js','Canvas',null,{id:row.id});persistLocal();scheduleSave();renderShapeSummary(shapeArray());proSetTool('select')});fabricLayoutCanvas.on('mouse:dblclick',e=>e.target&&editFabricText(e.target));fabricLayoutCanvas.on('selection:created',e=>{shapeSelectedId=e.selected?.[0]?.layoutId||'';updateShapeProperties()});fabricLayoutCanvas.on('selection:updated',e=>{shapeSelectedId=e.selected?.[0]?.layoutId||'';updateShapeProperties()});fabricLayoutCanvas.on('selection:cleared',()=>{shapeSelectedId='';updateShapeProperties()});fabricLayoutCanvas.on('mouse:down',e=>{if(e.e.button===2&&e.target){e.e.preventDefault();const row=items.find(o=>o.id===e.target.layoutId);openStationContextMenu(e.e,{shape:row,station:stationForShape(row)})}});if(scroll){scroll.scrollLeft=sx;scroll.scrollTop=sy}$('shapeZoomReset').textContent=Math.round(shapeZoom*100)+'%';updateShapeProperties()};
applyShapeZoom=function(){renderShapesCanvas()};
setShapeZoom=function(value){shapeZoom=Math.max(.5,Math.min(1.5,Math.round(value*10)/10));renderShapesCanvas()};

setActiveShapeTool=function(tool){activeShapeTool=tool;document.querySelectorAll('#shapeToolbar [data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===tool));if(fabricLayoutCanvas){fabricLayoutCanvas.isDrawingMode=tool==='pen'||tool==='polyline';if(fabricLayoutCanvas.isDrawingMode){fabricLayoutCanvas.freeDrawingBrush=new fabric.PencilBrush(fabricLayoutCanvas);fabricLayoutCanvas.freeDrawingBrush.color=$('shapeStrokeInput').value;fabricLayoutCanvas.freeDrawingBrush.width=+$('shapeStrokeWidth').value||2}}toast(tool==='select'?'Đã bật con trỏ chọn':'Kéo chuột để vẽ bằng Fabric.js')}

