/* Phase 2C responsive factory workflow. Desktop remains the authoritative Office editor. */
(()=>{
 const compact=()=>matchMedia('(max-width: 768px)').matches;
 const fmt=value=>Number(value||0).toFixed(2);
 const safe=value=>typeof esc==='function'?esc(value):String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
 const processFacts=station=>{const m=metrics(),cycle=stationCycle(station),ratio=m.neck?cycle/m.neck*100:0,jigs=getJigs(station);return{tt:stationTime(station),cycle,ratio,uph:cycle?Math.round(3600/cycle):0,jigs,equipment:jigs.map(jig=>jig.name||jig.eqType||jig.type).filter(Boolean).join(', ')}};
 function ensureLobToolbar(){const panel=$('mobileLobPanel');if(!panel||panel.dataset.ready)return;panel.dataset.ready='1';panel.innerHTML='<div class="mobile-filter-bar"><input id="mobileLobSearch" type="search" placeholder="Tìm STT hoặc công đoạn…"><div><button data-mobile-filter="all" class="active">Tất cả</button><button data-mobile-filter="neck">Neck</button><button data-mobile-filter="dkn">ĐKN</button><button data-mobile-filter="auto">Auto</button></div></div><div id="mobileLobCards" class="mobile-card-list"></div>';panel.querySelector('input').oninput=renderMobileLobCards;panel.querySelectorAll('[data-mobile-filter]').forEach(button=>button.onclick=()=>{panel.querySelectorAll('[data-mobile-filter]').forEach(item=>item.classList.toggle('active',item===button));renderMobileLobCards()})}
 function renderMobileLobCards(){const panel=$('mobileLobPanel');if(!panel)return;panel.hidden=!compact();if(!compact())return;ensureLobToolbar();const query=($('mobileLobSearch')?.value||'').trim().toLowerCase(),filter=panel.querySelector('[data-mobile-filter].active')?.dataset.mobileFilter||'all',m=metrics();let rows=model().processes.map((station,index)=>({station,index,facts:processFacts(station)}));rows=rows.filter(({station,index,facts})=>{const searchable=`${index+1} ${station.name} ${facts.equipment}`.toLowerCase();if(query&&!searchable.includes(query))return false;if(filter==='neck')return Math.abs(facts.cycle-m.neck)<.005;if(filter==='dkn')return stationSkills(station).length>0;if(filter==='auto')return !!station.auto||Number(station.mp)===0;return true});$('mobileLobCards').innerHTML=rows.map(({station,index,facts})=>`<article class="mobile-process-card ${Math.abs(facts.cycle-m.neck)<.005?'neck':''}" data-process-id="${safe(station.id)}"><header><b>${index+1}</b><strong>${safe(station.name)}</strong>${stationSkills(station).length?'<i>★</i>':''}</header><dl><dt>T/T</dt><dd>${fmt(facts.tt)} s</dd><dt>MP</dt><dd>${station.mp??0}</dd><dt>UPH</dt><dd>${facts.uph}</dd><dt>Neck</dt><dd><span class="mobile-ratio"><i style="width:${Math.min(100,facts.ratio)}%"></i></span>${Math.round(facts.ratio)}%</dd></dl><details><summary>Thiết bị / Jig</summary><p>${safe(facts.equipment||'Chưa khai báo')}</p></details>${can('tt.measure')?'<button class="mobile-measure" type="button">⏱ ĐO T/T</button>':''}</article>`).join('')||'<p class="mobile-empty">Không tìm thấy công đoạn.</p>';$('mobileLobCards').querySelectorAll('.mobile-measure').forEach(button=>button.onclick=()=>{const station=model().processes.find(item=>item.id===button.closest('article').dataset.processId);if(!station)return;if(editingModule!=='measure')enterEditMode('measure');openStopwatch(station)})}
 function renderMobileEquipment(){const panel=$('mobileEquipmentPanel');if(!panel)return;panel.hidden=!compact();if(!compact())return;const rows=model().processes.flatMap((station,index)=>getJigs(station).map((jig,jigIndex)=>({station,index,jig,jigIndex})));panel.innerHTML=`<div class="mobile-equipment-summary">${$('jigInventorySummary')?.innerHTML||''}</div><div class="mobile-card-list">${rows.map(({station,index,jig,jigIndex})=>`<article class="mobile-equipment-card" data-process-id="${safe(station.id)}" data-jig-index="${jigIndex}"><header><b>${index+1}</b><strong>${safe(station.name)}</strong></header><dl><dt>Loại</dt><dd>${safe(jig.eqType||jig.type||'Tool')}</dd><dt>Thiết bị / Jig</dt><dd>${safe(jig.name||'Chưa đặt tên')}</dd><dt>Setup</dt><dd>${Number(jig.setup||jig.setupTimeMin||0).toFixed(1)} phút</dd></dl>${can('equipment.edit')||can('jig.edit')?'<button class="mobile-equipment-edit" type="button">Chỉnh sửa</button>':''}</article>`).join('')||'<p class="mobile-empty">Model chưa có thiết bị hoặc Jig.</p>'}</div>`;panel.querySelectorAll('.mobile-equipment-edit').forEach(button=>button.onclick=()=>{if(!can('equipment.edit')&&!can('jig.edit'))return;enterEditMode('equipment');const card=button.closest('article'),station=model().processes.find(item=>item.id===card.dataset.processId),jig=getJigs(station)[+card.dataset.jigIndex],name=prompt('Tên thiết bị / Jig:',jig.name||'');if(name===null)return;const setup=prompt('Setup (phút):',jig.setup||0);jig.name=name.trim();jig.setup=Math.max(0,+setup||0);renderAll();scheduleSave();toast('Đã cập nhật thiết bị; nhấn Lưu thiết bị để ghi revision.')})}
 function fitMobileLayout(){if(!compact()||layoutEditing||!fabricLayoutCanvas)return;const canvas=ensureLayoutDocument().canvas,host=document.querySelector('.shapes-canvas-scroll'),width=canvas.widthMeters*canvas.pixelsPerMeter,height=canvas.heightMeters*canvas.pixelsPerMeter,viewWidth=Math.max(280,(host?.clientWidth||innerWidth)-16),viewHeight=Math.max(300,host?.clientHeight||innerHeight*.55),zoom=Math.max(.06,Math.min(2,Math.min(viewWidth/width,viewHeight/height)));fabricLayoutCanvas.setViewportTransform([zoom,0,0,zoom,(fabricLayoutCanvas.width-width*zoom)/2,(fabricLayoutCanvas.height-height*zoom)/2]);shapeZoom=zoom;fabricLayoutCanvas.requestRenderAll();const fit=$('mobileLayoutFit');if(fit)fit.textContent=`Fit ${Math.round(zoom*100)}%`}
 function inspectMobileObject(row){if(!row||!compact())return;const sheet=$('mobileObjectSheet'),facts=row.type==='process-station'&&typeof officeProcessFacts==='function'?officeProcessFacts(row):null;sheet.querySelector('#mobileObjectSheetBody').innerHTML=facts?`<span>Công đoạn ${safe(facts.no)}</span><h2>${safe(facts.name)}</h2><dl><dt>T/T</dt><dd>${fmt(facts.tt)} s</dd><dt>MP</dt><dd>${facts.mp}</dd><dt>Thiết bị / Jig</dt><dd>${safe(facts.equipment||'—')}</dd><dt>ĐKN</dt><dd>${facts.dkn?'★':'—'}</dd></dl>${can('tt.measure')?'<button data-mobile-measure-sheet class="mobile-measure">⏱ ĐO T/T</button>':''}`:`<span>Đối tượng Layout</span><h2>${safe(row.name||row.text||row.type)}</h2>`;sheet.showModal();sheet.querySelector('[data-mobile-measure-sheet]')?.addEventListener('click',()=>{sheet.close();if(editingModule!=='measure')enterEditMode('measure');openStopwatch(facts.process)})}
 function bindMobileCanvas(){if(!compact()||layoutEditing||!fabricLayoutCanvas)return;const upper=fabricLayoutCanvas.upperCanvasEl;if(!upper||upper.dataset.mobileViewerBound)return;upper.dataset.mobileViewerBound='1';let pointers=new Map(),lastDistance=0,lastTap=0;upper.style.touchAction='none';upper.addEventListener('pointerdown',event=>{pointers.set(event.pointerId,{x:event.clientX,y:event.clientY,startX:event.clientX,startY:event.clientY});upper.setPointerCapture(event.pointerId)});upper.addEventListener('pointermove',event=>{if(!pointers.has(event.pointerId))return;const previous=pointers.get(event.pointerId);pointers.set(event.pointerId,{...previous,x:event.clientX,y:event.clientY});if(pointers.size===1){const vpt=fabricLayoutCanvas.viewportTransform;vpt[4]+=event.clientX-previous.x;vpt[5]+=event.clientY-previous.y;fabricLayoutCanvas.requestRenderAll()}else if(pointers.size===2){const [a,b]=[...pointers.values()],distance=Math.hypot(a.x-b.x,a.y-b.y);if(lastDistance){const factor=distance/lastDistance,center=new fabric.Point((a.x+b.x)/2-upper.getBoundingClientRect().left,(a.y+b.y)/2-upper.getBoundingClientRect().top),zoom=Math.max(.06,Math.min(4,fabricLayoutCanvas.getZoom()*factor));fabricLayoutCanvas.zoomToPoint(center,zoom);shapeZoom=zoom}lastDistance=distance}});const finish=event=>{const point=pointers.get(event.pointerId);pointers.delete(event.pointerId);if(pointers.size<2)lastDistance=0;if(point&&Math.hypot(event.clientX-point.startX,event.clientY-point.startY)<8){const now=Date.now();if(now-lastTap<320)fitMobileLayout();else{const target=fabricLayoutCanvas.findTarget(event);const row=shapeArray().find(item=>item.id===target?.layoutId);if(row)inspectMobileObject(row)}lastTap=now}};upper.addEventListener('pointerup',finish);upper.addEventListener('pointercancel',finish)}
 function ensureLayoutControls(){if(!compact()||$('mobileLayoutControls'))return;const zone=document.querySelector('.shapes-zone');if(!zone)return;const controls=document.createElement('div');controls.id='mobileLayoutControls';controls.innerHTML='<button data-mobile-zoom="out">−</button><button id="mobileLayoutFit">Fit</button><button data-mobile-zoom="in">＋</button><button data-mobile-full>Toàn màn hình Layout</button>';zone.querySelector('.shapes-canvas-scroll')?.before(controls);controls.querySelector('[data-mobile-zoom="out"]').onclick=()=>proZoom(.8);controls.querySelector('[data-mobile-zoom="in"]').onclick=()=>proZoom(1.25);$('mobileLayoutFit').onclick=fitMobileLayout;controls.querySelector('[data-mobile-full]').onclick=()=>zone.classList.toggle('mobile-layout-fullscreen')}
 const baseProcess=renderProcessTable;renderProcessTable=function(){baseProcess();renderMobileLobCards()};
 const baseJigs=renderJigInventory;renderJigInventory=function(){baseJigs();renderMobileEquipment()};
 const baseShapes=renderShapesCanvas;renderShapesCanvas=function(){baseShapes();if(compact()&&!layoutEditing){ensureLayoutControls();requestAnimationFrame(()=>{fitMobileLayout();bindMobileCanvas()});setTimeout(()=>{fitMobileLayout();bindMobileCanvas()},180)}};
 document.querySelector('[data-mobile-sheet-close]')?.addEventListener('click',()=>$('mobileObjectSheet').close());
 if(compact()){
  $('stopwatchPause').textContent='Dừng';
  $('stopwatchReset').textContent='Đo lại';
  $('stopwatchReset').onclick=()=>{stopwatchReset();stopwatchStart()};
 }
 addEventListener('resize',()=>{renderMobileLobCards();renderMobileEquipment();if(compact()&&!layoutEditing)requestAnimationFrame(fitMobileLayout)});
 if(compact()){renderMobileLobCards();renderMobileEquipment();ensureLayoutControls();requestAnimationFrame(()=>{fitMobileLayout();bindMobileCanvas()});setTimeout(()=>{fitMobileLayout();bindMobileCanvas()},180)}
 globalThis.ISTMobileUX={fmt,renderMobileLobCards,renderMobileEquipment,fitMobileLayout};
})();
