let activeView='overview',layoutScale=1,historyOffset=0,historyModel='',historyRows=[],selectedObjectUid='',layoutClipboard=null,layoutEditMode=true,layoutVisualMode='excel',lobEditMode=false;
const STUDIO={width:2060,origin:260,scale:60,beltY:250,beltHeight:70};
function modelType(){return model().type||(/block/i.test(model().name)?'block':'normal')}
function ensureIqcFirst(){const rows=model().processes,index=rows.findIndex(s=>norm(s.name)==='IQC');if(index>0)rows.unshift(rows.splice(index,1)[0])}
function normalizeStationSlots(rows){
  if(model().slotSchemaVersion!==2){const laser=rows.find(s=>norm(s.name).includes('LASER WELD')||norm(s.name).includes('HAN LASER')),visionStart=rows.findIndex(s=>norm(s.name).includes('VISION LASER')),coordinate=s=>Number.isFinite(+s.excelColumn)?+s.excelColumn:Number(s.x)||Number(s.slotIndex)||0;for(const [index,s] of rows.entries()){if(s===laser){s.side='HEAD';continue}s.side=visionStart>=0?(index>=visionStart?'BOTTOM':'TOP'):(Number(s.y)>180?'BOTTOM':'TOP')}const top=rows.filter(s=>s!==laser&&s.side==='TOP').sort((a,b)=>coordinate(a)-coordinate(b)),bottom=rows.filter(s=>s!==laser&&s.side==='BOTTOM').sort((a,b)=>coordinate(a)-coordinate(b));top.forEach((s,i)=>{s.stt=top.length-i;s.slotIndex=i+1});if(laser){laser.stt=top.length+1;laser.slotIndex=0}bottom.forEach((s,i)=>{s.stt=top.length+2+i;s.slotIndex=i+1});model().slotSchemaVersion=2}
  for(const s of rows){const welding=norm(s.name).includes('LASER WELD')||norm(s.name).includes('HAN LASER');s.side=s.side||welding&&'HEAD'||(Number(s.excelBlock)===1||(!Number.isInteger(s.excelBlock)&&Number(s.y)>100)?'BOTTOM':'TOP');if(s.isActive===undefined)s.isActive=true}
  for(const side of ['TOP','BOTTOM']){const group=rows.filter(s=>s.side===side).sort((a,b)=>(Number.isFinite(+a.excelColumn)?+a.excelColumn:+a.x||0)-(Number.isFinite(+b.excelColumn)?+b.excelColumn:+b.x||0)),used=new Set();for(const [index,s] of group.entries()){let slot=Math.max(1,Math.min(27,Number(s.slotIndex)||Number(s.excelColumn)+1||index+1));while(used.has(slot)&&slot<27)slot++;if(used.has(slot))slot=[...Array(27)].map((_,i)=>i+1).find(v=>!used.has(v))||27;s.slotIndex=slot;used.add(slot)}}
}
function physicalObjects(){
  const objects=[],belt=model().layoutSettings?.belt||{};normalizeStationSlots(model().processes);
  objects.push({uid:'model:belt',scope:'model',key:'belt',kind:'belt',x:Number(belt.x==null||Number(belt.x)===40?STUDIO.origin:belt.x),y:Number(belt.y??STUDIO.beltY),width:1620,height:STUDIO.beltHeight,rotation:Number(belt.rotation)||0,label:'Băng tải 27 m'});
  for(const [index,s] of model().processes.entries()){
    const welding=norm(s.name).includes('LASER WELD')||norm(s.name).includes('HAN LASER'),side=s.side||welding&&'HEAD'||(Number(s.excelBlock)===1||(!Number.isInteger(s.excelBlock)&&Number(s.y)>100)?'BOTTOM':'TOP'),slot=Math.max(1,Math.min(27,Number(s.slotIndex)||Number(s.excelColumn)+1||Math.round((+s.x||0)/78)+1||index+1));s.side=side;s.slotIndex=slot;if(s.isActive===undefined)s.isActive=true;if(!s.isActive)continue;let x=side==='HEAD'?50:STUDIO.origin+(slot-1)*STUDIO.scale,y=side==='HEAD'?210:side==='TOP'?145:370;
    const positionOnly=positionUsage([s]).positionOnly>0,jigs=getJigs(s);
    const add=(key,kind,bx,by,width,height,extra={})=>{const saved=s.layoutObjects?.[key],locked=['table','machine','welder'].includes(kind);objects.push({uid:s.id+':'+key,scope:'station',station:s,index,key,kind,x:Math.max(40,Math.min(2020-width,Number(locked?bx:saved?.x??bx)||40)),y:Math.max(40,Number(locked?by:saved?.y??by)||40),rotation:Number(saved?.rotation)||0,width,height,...extra})};
    add(welding?'welder':positionOnly?'machine':'table',welding?'welder':positionOnly?'machine':'table',x,y,welding?180:30,welding?120:30,{label:welding?'LASER':(norm(s.name).match(/\b(DMC|WLT|VSWR)\b/)||[s.auto?'AUTO':''])[0]});
    const base=objects.at(-1);
    if(s.auto&&!positionOnly)add('machine','machine',base.x,base.y-46,44,30,{label:'AUTO'});
    if(+s.mp>0)add('person','person',side==='HEAD'?base.x+65:base.x-26,side==='HEAD'?base.y+32:base.y,24,50,{label:String(s.mp)});
    let pressCount=0,attachCount=0;
    jigs.forEach((j,n)=>{j.id=j.id||'legacy-'+n;const type=jigType(j),press=type==='press';add('jig:'+j.id,type,press?base.x+(pressCount++%3)*19:base.x+3+(attachCount++%3)*14,press?base.y-40-Math.floor((pressCount-1)/3)*34:base.y+3+Math.floor((attachCount-1)/3)*13,press?16:12,press?30:12,{jig:j,label:press?'V3':type==='attach'?'A':'T'})});
  }
  for(const extra of model().layoutExtras||[]){const station=model().processes.find(s=>s.id===extra.stationId)||null;objects.push({...extra,uid:'extra:'+extra.id,scope:'extra',isExtra:true,station,index:station?model().processes.indexOf(station):-1,key:extra.id,x:Number(extra.x)||60,y:Number(extra.y)||80,rotation:Number(extra.rotation)||0,width:Number(extra.width)||48,height:Number(extra.height)||30})}
  return objects;
}
function glyph(o){
  if(o.kind==='belt')return `<rect width="1620" height="70" rx="2" fill="#00ad51" stroke="#146f3b" stroke-width="2"/><rect y="23" width="1620" height="24" fill="#c0eec7"/><path d="M20 35H1600" stroke="#78c88b" stroke-width="2" stroke-dasharray="18 12"/><text x="810" y="40" text-anchor="middle" font-size="13" fill="#164d31" font-weight="bold">BĂNG TẢI 27 m</text>`;
  if(o.kind==='person')return `<rect x="2" y="18" width="20" height="17" rx="5" fill="#c5e8ef" stroke="#176176"/><path d="M5 33v5M19 33v5" stroke="#176176" stroke-width="2"/><circle cx="12" cy="9" r="6" fill="#7edcf0" stroke="#145e70" stroke-width="1.5"/><path d="M7 17c1-4 9-4 10 0l1 10H6Z" fill="#10b9de" stroke="#145e70" stroke-width="1.4"/><path d="M7 20 1 15M17 20l6-5" stroke="#10a5c8" stroke-width="3" stroke-linecap="round"/><circle cx="1" cy="15" r="2" fill="#7edcf0"/><circle cx="23" cy="15" r="2" fill="#7edcf0"/><text x="12" y="49" text-anchor="middle" font-size="10" font-weight="bold">${esc(o.label)} MP</text>`;
  if(o.kind==='table')return `<rect width="${o.width}" height="30" fill="#fbf7e8" stroke="#5d6d68" stroke-width="2"/><path d="M4 30v5M${o.width-4} 30v5" stroke="#5d6d68" stroke-width="2"/>`;
  if(o.kind==='welder')return `<rect width="${o.width}" height="${o.height}" rx="4" fill="#ffc928" stroke="#513d00" stroke-width="3"/><path d="M10 10h${o.width-20}v24H10z" fill="#fff2aa" stroke="#725700" stroke-width="2"/><rect x="14" y="48" width="58" height="54" fill="#263d46"/><circle cx="${o.width-42}" cy="62" r="11" fill="#eb4f3d" stroke="#6e160e" stroke-width="2"/><path d="M${o.width-74} 94h58M${o.width-66} 82h42" stroke="#6f5400" stroke-width="4"/><text x="${o.width/2}" y="28" text-anchor="middle" font-size="16" font-weight="900">LASER WELDING</text><text x="${o.width/2}" y="${o.height+16}" text-anchor="middle" font-size="11" font-weight="bold">MÁY HÀN 3 m × 2 m</text>`;
  if(o.kind==='machine')return `<rect width="${o.width}" height="30" fill="#bfe5ec" stroke="#144a5c" stroke-width="2"/><rect x="4" y="3" width="${o.width-8}" height="8" fill="#fff" stroke="#144a5c"/><text x="${o.width/2}" y="24" font-size="10" text-anchor="middle" font-weight="bold">${esc(o.label)}</text>`;
  const press=o.kind==='press';return `<rect width="${o.width}" height="${o.height}" fill="${press?'#f6c6a3':o.kind==='attach'?'#c1efaa':'#d6e6f5'}" stroke="#5a5a44"/><path d="M2 3H${o.width-2}M2 ${o.height-3}H${o.width-2}" stroke="#7c8172"/><text x="${o.width/2}" y="${press?18:9}" font-size="${press?9:8}" text-anchor="middle" font-weight="bold">${o.label}</text>`;
}
function wrapProcessName(value,max=13,limit=3){const words=String(value||'').replace(/\s+/g,' ').trim().split(' '),lines=[];for(const word of words){const current=lines.at(-1)||'';if(!current||current.length+1+word.length>max)lines.push(word);else lines[lines.length-1]=current+' '+word}if(lines.length>limit){lines[limit-1]=lines.slice(limit-1).join(' ');lines.length=limit;if(lines[limit-1].length>max+4)lines[limit-1]=lines[limit-1].slice(0,max+3)+'…'}return lines}
function objectTransform(o){return `translate(${o.x} ${o.y}) rotate(${o.rotation||0} ${o.width/2} ${o.height/2})`}
function renderEquipmentDiagram(){
  const objects=physicalObjects(),height=Math.max(650,...objects.map(o=>o.y+130)),width=STUDIO.width;
  let marks='';for(let meter=0;meter<=33;meter++){const x=40+meter*60;marks+=`<line x1="${x}" y1="30" x2="${x}" y2="38" stroke="#9eb0aa"/><text x="${x}" y="20" font-size="10" text-anchor="middle" fill="#516a62">${meter}</text>`}
  const labels=objects.filter(o=>!o.isExtra&&o.station&&(o.kind==='table'||o.kind==='welder'||(o.kind==='machine'&&positionUsage([o.station]).positionOnly))).map(o=>{const head=o.kind==='welder',lines=wrapProcessName(o.station.name,head?16:9,head?3:4),center=o.x+o.width/2,labelY=o.y+(head?132:50),boxWidth=head?150:58,lineHeight=head?11:9;return `<g data-station="${esc(o.station.id)}" class="object-label"><rect x="${center-boxWidth/2}" y="${labelY-12}" width="${boxWidth}" height="${30+lines.length*lineHeight}" rx="3" fill="#fff" fill-opacity=".96" stroke="#d5e0dc"/><text x="${center}" y="${labelY}" text-anchor="middle" font-size="${head?12:10}" font-weight="bold">${o.station.stt||o.index+1}${o.station.critical?' ★':''}</text><text x="${center}" y="${labelY+12}" text-anchor="middle" font-size="${head?8:6.5}" font-weight="600">${lines.map((line,i)=>`<tspan x="${center}" dy="${i?lineHeight:0}">${esc(line)}</tspan>`).join('')}</text>${stationSkills(o.station).length?`<text x="${center}" y="${labelY+24+lines.length*lineHeight}" text-anchor="middle" font-size="7" fill="#d22b22">★ ĐKN</text>`:''}</g>`}).join('');
  const graphics=objects.map((o,n)=>{const label=o.kind==='belt'?'Băng tải 27 m':o.station?`${o.index+1}. ${o.station.name} · ${o.kind}`:`${o.kind} bản sao`;return `<g class="layout-object ${o.isExtra?'layout-extra':''}" data-object="${n}" tabindex="0" role="button" aria-label="${esc(label)}" transform="${objectTransform(o)}"><title>${esc(label+(o.jig?.name?' · '+o.jig.name:''))}</title>${o.uid===selectedObjectUid?`<rect x="-4" y="-4" width="${o.width+8}" height="${o.height+8}" fill="none" stroke="#e29121" stroke-width="3" stroke-dasharray="6 3"/>`:''}${glyph(o)}</g>`}).join('');
  const svg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${height}" width="${width}" height="${height}" role="img" aria-label="Layout ${esc(model().name)} · chiều rộng 33 m"><rect x="40" y="30" width="1980" height="${height-45}" fill="#fff" stroke="#79988b"/>${marks}${graphics}${labels}</svg>`;
  $('equipmentDiagram').innerHTML=svg;applyLayoutZoom();
  $('equipmentDiagram').querySelectorAll('.layout-object').forEach(el=>{const o=objects[+el.dataset.object];el.onclick=()=>{if(el.dataset.dragged==='1'){el.dataset.dragged='0';return}selectLayoutObject(o)};el.onkeydown=e=>{if(e.key==='Enter'){selectLayoutObject(o)}};if(canEdit()&&layoutEditMode)el.onpointerdown=e=>dragObject(e,o,objects)});
  $('equipmentDiagram').querySelectorAll('.object-label').forEach(el=>el.onclick=()=>select(el.dataset.station));
  updateLayoutToolbar();
}
function applyLayoutZoom(){const svg=$('equipmentDiagram').querySelector('svg');if(!svg)return;const value=$('layoutZoom').value;layoutScale=value==='fit'?Math.max(.15,($('equipmentDiagram').clientWidth-16)/STUDIO.width):Number(value)||1;svg.style.width=STUDIO.width*layoutScale+'px';svg.style.height=Number(svg.getAttribute('viewBox').split(' ')[3])*layoutScale+'px'}
function referenceSlug(name){let slug=norm(name).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');if(/^x40/.test(slug))slug='x406';return slug}
function renderExcelReference(){
  if(!$('excelReferenceImage'))return;const custom=model().referenceImage,slug=referenceSlug(model().name),image=$('excelReferenceImage');image.hidden=false;image.onerror=()=>{image.onerror=null;image.hidden=true;layoutVisualMode='interactive';document.body.dataset.layoutMode='interactive';$('excelLayoutModeBtn').classList.remove('active');$('interactiveLayoutModeBtn').classList.add('active');$('excelReferenceName').textContent='Ảnh Excel chưa khả dụng · đã chuyển sang layout trực quan';applyLayoutZoom();toast('Đã chuyển sang layout trực quan vì ảnh Excel chưa tải được')};image.src=custom||`./layout-reference/${slug}.png`;$('excelReferenceName').textContent=`${model().name} · ${model().version==='Imported'?'Bản gốc':model().version}${custom?' · ảnh đã cập nhật':''}`;document.body.dataset.layoutMode=layoutVisualMode;$('excelLayoutModeBtn').classList.toggle('active',layoutVisualMode==='excel');$('interactiveLayoutModeBtn').classList.toggle('active',layoutVisualMode==='interactive');$('replaceReferenceBtn').hidden=!canEdit()
}
function setLayoutVisualMode(mode){layoutVisualMode=mode;renderExcelReference();if(mode==='interactive')applyLayoutZoom()}
function importReferenceImage(file){if(!canEdit()||!file)return;if(file.size>6*1024*1024)return toast('Ảnh layout cần nhỏ hơn 6 MB.');const reader=new FileReader();reader.onload=()=>{snapshot();model().referenceImage=reader.result;model().referenceImageName=file.name;renderExcelReference();scheduleSave();toast('Đã cập nhật ảnh layout cho phiên bản hiện tại')};reader.onerror=()=>toast('Không đọc được ảnh layout.');reader.readAsDataURL(file)}
function dragObject(e,o,objects){
  if(e.button!==0)return;e.preventDefault();const el=e.currentTarget,svg=el.ownerSVGElement,point=()=>svg.createSVGPoint();
  const local=ev=>{const p=point();p.x=ev.clientX;p.y=ev.clientY;return p.matrixTransform(svg.getScreenCTM().inverse())};
  const initial=local(e);let moved=false,newX=o.x,newY=o.y;el.setPointerCapture(e.pointerId);
  el.onpointermove=ev=>{const p=local(ev);if(!moved&&Math.hypot(p.x-initial.x,p.y-initial.y)<3)return;if(!moved){snapshot();moved=true}newX=Math.max(40,Math.min(2020-o.width,Math.round((o.x+p.x-initial.x)/3)*3));newY=Math.max(40,Math.min(svg.viewBox.baseVal.height-120,Math.round((o.y+p.y-initial.y)/3)*3));el.setAttribute('transform',`translate(${newX} ${newY}) rotate(${o.rotation||0} ${o.width/2} ${o.height/2})`)};
  const done=()=>{el.onpointermove=null;el.onpointerup=null;el.onpointercancel=null;if(!moved)return;if(o.station&&['table','machine'].includes(o.kind)){const oldSide=o.station.side,oldSlot=o.station.slotIndex,nextSide=newY<STUDIO.beltY?'TOP':'BOTTOM',nextSlot=Math.max(1,Math.min(27,Math.round((newX-STUDIO.origin)/STUDIO.scale)+1)),other=model().processes.find(s=>s!==o.station&&s.side===nextSide&&s.slotIndex===nextSlot);if(other){other.side=oldSide;other.slotIndex=oldSlot}o.station.side=nextSide;o.station.slotIndex=nextSlot;normalizeStationSlots(model().processes)}else saveObjectPosition(o,newX,newY);if(o.kind==='table'&&o.station){for(const a of objects.filter(a=>a.station===o.station&&['attach','tool'].includes(a.kind)))saveObjectPosition(a,Math.max(40,Math.min(2020-a.width,a.x+newX-o.x)),Math.max(40,a.y+newY-o.y))}if(o.station&&['table','machine','welder'].includes(o.kind))reorderProcessesByLayout();selectedObjectUid=o.uid;selectedId=o.station?.id||selectedId;el.dataset.dragged='1';renderAll();scheduleSave();toast('Đã đổi vị trí '+({person:'người',table:'bàn',machine:'máy',welder:'máy hàn',belt:'băng tải'}[o.kind]||'thiết bị'))};el.onpointerup=done;el.onpointercancel=done;
}
function saveObjectPosition(o,x=o.x,y=o.y,rotation=o.rotation||0){
  if(o.scope==='model'){model().layoutSettings=model().layoutSettings||{};model().layoutSettings.belt={x,y,rotation};return}
  if(o.scope==='extra'){const extra=(model().layoutExtras||[]).find(item=>item.id===o.key);if(extra)Object.assign(extra,{x,y,rotation});return}
  const s=o.station;if(!s)return;s.layoutObjects=s.layoutObjects||{};s.layoutObjects[o.key]={...(s.layoutObjects[o.key]||{}),x,y,rotation};
}
function selectLayoutObject(o){selectedObjectUid=o.uid;if(o.station)select(o.station.id);else{renderEquipmentDiagram();updateLayoutToolbar()}}
function selectedLayoutObject(){return physicalObjects().find(o=>o.uid===selectedObjectUid)}
function objectDisplayName(o){if(!o)return'Chọn người, bàn, máy hoặc băng tải';const kind={belt:'Băng tải 27 m',person:'Người ngồi',table:'Bàn',machine:'Máy',welder:'Máy hàn Laser',press:'Jig Press V3',attach:'Jig Attach',tool:'Tool'}[o.kind]||o.kind;return o.station?`${kind} · ${o.index+1}. ${o.station.name}`:o.isExtra?`${kind} · bản sao`:kind}
function updateLayoutToolbar(){if(!$('layoutEditorToolbar'))return;const o=selectedLayoutObject(),editable=canEdit()&&layoutEditMode;$('layoutEditorToolbar').hidden=!canEdit();$('selectedObjectName').textContent=objectDisplayName(o);$('layoutLockBtn').textContent=layoutEditMode?'Đang chỉnh sửa':'Đã khóa bố cục';$('layoutLockBtn').classList.toggle('active',layoutEditMode);$('rotateObjectBtn').disabled=!editable||!o;$('copyObjectBtn').disabled=!editable||!o||o.kind==='belt';$('duplicateObjectBtn').disabled=!editable||!o||o.kind==='belt';$('pasteObjectBtn').disabled=!editable||!layoutClipboard;$('snapObjectBtn').disabled=!editable||!o;$('deleteObjectBtn').disabled=!editable||!o?.isExtra}
function rotateSelectedObject(){const o=selectedLayoutObject();if(!o||!canEdit()||!layoutEditMode)return;snapshot();saveObjectPosition(o,o.x,o.y,((o.rotation||0)+90)%360);renderEquipmentDiagram();scheduleSave();toast('Đã xoay 90°')}
function copySelectedObject(){const o=selectedLayoutObject();if(!o||o.kind==='belt')return;layoutClipboard={kind:o.kind,width:o.width,height:o.height,label:o.label||'',jig:o.jig?structuredClone(o.jig):null,stationId:o.station?.id||null,rotation:o.rotation||0};updateLayoutToolbar();toast('Đã sao chép '+objectDisplayName(o))}
function pasteLayoutObject(){if(!layoutClipboard||!canEdit()||!layoutEditMode)return;const base=selectedLayoutObject(),id='obj-'+Date.now()+'-'+Math.random().toString(36).slice(2,6),extra={...structuredClone(layoutClipboard),id,x:Math.min(1960,(base?.x||80)+34),y:Math.min(620,(base?.y||80)+34)};snapshot();model().layoutExtras=model().layoutExtras||[];model().layoutExtras.push(extra);selectedObjectUid='extra:'+id;renderAll();scheduleSave();toast('Đã dán bản sao; kéo đến vị trí cần đặt')}
function duplicateSelectedObject(){copySelectedObject();pasteLayoutObject()}
function snapSelectedObject(){const o=selectedLayoutObject();if(!o)return;snapshot();saveObjectPosition(o,Math.round(o.x/10)*10,Math.round(o.y/10)*10,o.rotation||0);renderEquipmentDiagram();scheduleSave();toast('Đã căn theo lưới 10 px')}
function deleteSelectedObject(){const o=selectedLayoutObject();if(!o?.isExtra)return;snapshot();model().layoutExtras=(model().layoutExtras||[]).filter(item=>item.id!==o.key);selectedObjectUid='';renderAll();scheduleSave();toast('Đã xóa bản sao khỏi layout')}
function reorderProcessesByLayout(){const rows=model().processes,objects=physicalObjects(),point=new Map();for(const o of objects){if(!o.station||o.isExtra||!['table','machine','welder'].includes(o.kind)||point.has(o.station.id))continue;point.set(o.station.id,{x:o.x,y:o.y})}rows.sort((a,b)=>{const ai=norm(a.name)==='IQC',bi=norm(b.name)==='IQC';if(ai!==bi)return ai?-1:1;const pa=point.get(a.id)||{x:0,y:9999},pb=point.get(b.id)||{x:0,y:9999};return Math.round(pa.y/90)-Math.round(pb.y/90)||pa.x-pb.x});ensureIqcFirst()}
function renderJigInventory(){
  if(!$('jigInventoryBody'))return;const records=model().processes.flatMap((s,i)=>getJigs(s).map(j=>({s,i,j}))),setup=records.reduce((n,r)=>n+(+r.j.setup||0),0);
  $('jigViewTitle').textContent=`Jig · ${model().name} · ${model().version==='Imported'?'Bản gốc':model().version}`;
  $('jigInventorySummary').innerHTML=`<b>${records.length} Jig / Tool</b><span>Press: ${records.filter(r=>jigType(r.j)==='press').length}</span><span>Attach: ${records.filter(r=>jigType(r.j)==='attach').length}</span><span>Tool: ${records.filter(r=>jigType(r.j)==='tool').length}</span><span>Setup: ${setup.toFixed(1)} phút</span>`;
  const typeValue=j=>j.eqType||(jigType(j)==='press'?'V3':jigType(j)==='attach'?'ATTACH':'TEST'),options=['V3','ATTACH','DINO','C-CLIP','TEST','AUTO'];
  $('jigStationSelect').innerHTML=model().processes.map((s,i)=>`<option value="${esc(s.id)}">${s.stt||i+1}. ${esc(s.name)}</option>`).join('');
  $('jigInventoryBody').innerHTML=records.length?records.map(({s,i,j},n)=>`<tr data-station="${esc(s.id)}" data-jig="${esc(j.id||(j.id='j-'+Date.now()+'-'+n))}"><td>${n+1}</td><td>${s.stt||i+1}</td><td><b>${esc(s.name)}</b></td><td>${canEdit()?`<select class="inventory-jig-type">${options.map(v=>`<option value="${v}" ${typeValue(j)===v?'selected':''}>${v}</option>`).join('')}</select>`:typeValue(j)}</td><td>${canEdit()?`<input class="inventory-jig-name" value="${esc(j.name||'')}" placeholder="Mã/Tên Jig">`:esc(j.name||'Chưa đặt tên')}</td><td>${canEdit()?`<input class="inventory-jig-setup" type="number" min="0" step="0.1" value="${+j.setup||0}">`:(+j.setup||'Chưa đo')}</td><td>${canEdit()?'<button class="jig-delete-inline" type="button" title="Xóa Jig">×</button>':''}</td></tr>`).join(''):'<tr><td colspan="7">Chưa khai báo Jig cho model này. Chọn công đoạn và nhấn “Thêm Jig”.</td></tr>';
  $('jigInventoryBody').querySelectorAll('tr[data-jig]').forEach(row=>{const station=model().processes.find(s=>s.id===row.dataset.station),jig=getJigs(station).find(j=>j.id===row.dataset.jig),refresh=()=>{renderAll();scheduleSave()};row.querySelector('.inventory-jig-type')?.addEventListener('change',e=>{snapshot();jig.eqType=e.target.value;jig.type=e.target.value==='V3'?'press':e.target.value==='ATTACH'?'attach':'tool';refresh()});row.querySelector('.inventory-jig-name')?.addEventListener('change',e=>{snapshot();jig.name=e.target.value.trim();refresh()});row.querySelector('.inventory-jig-setup')?.addEventListener('change',e=>{snapshot();jig.setup=Math.max(0,+e.target.value||0);refresh()});row.querySelector('.jig-delete-inline')?.addEventListener('click',()=>{snapshot();station.jigs=getJigs(station).filter(j=>j.id!==jig.id);refresh()})});
}
function renderExcelProcessForm(){
  if(!$('excelProcessGrid'))return;const rows=model().processes,objects=physicalObjects(),counts=kind=>objects.filter(o=>o.kind===kind).length;
  $('equipmentLegend').innerHTML=[['person','Người ngồi',metrics().mp],['table','Bàn',counts('table')],['welder','Máy hàn',counts('welder')],['machine','Máy / Test',counts('machine')],['press','Jig Press V3',counts('press')],['attach','Jig Attach',counts('attach')],['tool','Tool',counts('tool')],['critical','Trọng điểm',rows.filter(s=>s.critical).length]].map(([kind,label,value])=>`<article data-kind="${kind}"><i>${kind==='person'?'●':kind==='table'?'▭':kind==='welder'?'LAS':kind==='press'?'V3':kind==='attach'?'A':kind==='critical'?'★':'▣'}</i><span>${label}<b>${value}</b></span></article>`).join('');
  const groups=new Map();rows.forEach((s,i)=>{const lane=Number.isInteger(s.excelBlock)?s.excelBlock:Math.max(0,Math.round(((+s.y||60)-60)/94));if(!groups.has(lane))groups.set(lane,[]);groups.get(lane).push({s,i})});
  const card=({s,i})=>{const jigs=getJigs(s),jigText=jigs.map(j=>`<span class="jig-chip ${jigType(j)}">${jigType(j)==='press'?'V3':jigType(j)==='attach'?'A':'T'} · ${esc(j.name||'Chưa đặt tên')}</span>`).join('')||'<span class="jig-chip empty">Chưa có Jig</span>';return `<article class="excel-process-card ${s.critical?'critical':''}" data-id="${esc(s.id)}"><div class="excel-process-no">${i+1}${s.critical?' ★':''}</div><strong>${esc(s.name)}</strong><div class="excel-process-values"><span><small>T/T</small>${(+s.time||0).toFixed(2)}s</span><span><small>MP</small>${s.auto?'AUTO':s.mp}</span></div><div class="excel-process-jigs">${jigText}</div>${canEdit()?'<button class="excel-add-jig" type="button">+ Jig</button>':''}</article>`};
  $('excelProcessGrid').innerHTML=[...groups.entries()].sort((a,b)=>a[0]-b[0]).map(([lane,items])=>`<div class="excel-process-lane"><div class="excel-lane-label">Dải ${lane+1}</div><div class="excel-process-row">${items.sort((a,b)=>(Number.isFinite(a.s.excelColumn)?a.s.excelColumn:+a.s.x||0)-(Number.isFinite(b.s.excelColumn)?b.s.excelColumn:+b.s.x||0)).map(card).join('')}</div></div>`).join('');
  $('excelProcessGrid').querySelectorAll('.excel-process-card').forEach(el=>{el.onclick=e=>{select(el.dataset.id);if(e.target.closest('.excel-add-jig'))$('addJigBtn').click()}});
}
function renderSlotControls(){
  if(!$('slotControlPanel'))return;const rows=model().processes;
  const sideRow=(side,label)=>{const slots=Array.from({length:27},(_,i)=>{const slot=i+1,s=rows.find(x=>(x.side||((Number(x.excelBlock)===1)?'BOTTOM':'TOP'))===side&&Number(x.slotIndex||Number(x.excelColumn)+1)===slot),active=!!s&&s.isActive!==false;return `<label class="slot-toggle ${active?'active':''} ${s?'':'empty'}" title="${s?esc((s.stt||rows.indexOf(s)+1)+'. '+s.name):'Slot trống'}"><input type="checkbox" data-side="${side}" data-slot="${slot}" ${active?'checked':''} ${!s||!canEdit()?'disabled':''}><span>${slot}</span></label>`}).join('');return `<div class="slot-row"><b>${label}</b><div>${slots}</div></div>`};
  $('slotControlPanel').innerHTML=`<div class="slot-help"><b>27 SLOT / CHIỀU</b><span>Bàn 0,5 m + khoảng cách 0,5 m. Bỏ chọn để tạo khoảng trống.</span></div>${sideRow('TOP','TOP')}${sideRow('BOTTOM','BOTTOM')}`;
  $('slotControlPanel').querySelectorAll('input:not(:disabled)').forEach(input=>input.onchange=()=>{const station=rows.find(s=>(s.side||((Number(s.excelBlock)===1)?'BOTTOM':'TOP'))===input.dataset.side&&Number(s.slotIndex||Number(s.excelColumn)+1)===+input.dataset.slot);if(!station)return;snapshot();station.isActive=input.checked;renderAll();scheduleSave();toast(`${input.checked?'Đã bật':'Đã tắt'} slot ${input.dataset.slot} · ${input.dataset.side}`)});
}
function renderProcessMatrix(){
  if(!$('processMatrix'))return;normalizeStationSlots(model().processes);const groups=[['HEAD','ĐẦU CHUYỀN'],['TOP','NHÁNH TRÊN · THỨ TỰ GIẢM DẦN'],['BOTTOM','NHÁNH DƯỚI · THỨ TỰ TĂNG DẦN']].map(([side,label])=>({side,label,rows:model().processes.filter(s=>s.side===side).sort((a,b)=>side==='TOP'?(+b.stt||0)-(+a.stt||0):(+a.stt||0)-(+b.stt||0))})).filter(g=>g.rows.length),disabled=canEdit()?'':'disabled';
  const plain=(value,s,cls='')=>`<td data-id="${esc(s.id)}" class="${!s.isActive?'inactive ':''}${cls}">${value}</td>`;
  const edit=(s,kind,value,type='text')=>canEdit()?`<input class="matrix-edit matrix-${kind}" data-id="${esc(s.id)}" type="${type}" ${type==='number'?'min="0" step="0.01"':''} value="${esc(value)}" ${disabled}>`:esc(value);
  const lane=group=>{const rows=group.rows,sumTime=rows.reduce((n,s)=>n+(+s.time||0),0),sumMp=rows.reduce((n,s)=>n+(+s.mp||0),0);return `<section class="matrix-lane"><b>${group.label}</b><table><tbody><tr><th>STT Trạm</th>${rows.map(s=>plain(s.stt||model().processes.indexOf(s)+1,s)).join('')}<td class="total">TOTAL</td></tr><tr><th>Tên Process</th>${rows.map(s=>plain(edit(s,'name',s.name),s,'process-name')).join('')}<td class="total">${rows.length} trạm</td></tr><tr><th>T/T Avg</th>${rows.map(s=>plain(edit(s,'time',(+s.time||0).toFixed(2),'number'),s)).join('')}<td class="total">${sumTime.toFixed(2)}</td></tr><tr><th>MP</th>${rows.map(s=>plain(edit(s,'mp',s.auto?0:+s.mp||0,'number'),s)).join('')}<td class="total">${sumMp}</td></tr></tbody></table></section>`};
  $('processMatrix').innerHTML=groups.map(lane).join('');
  $('processMatrix').querySelectorAll('td[data-id]').forEach(cell=>cell.onclick=e=>{if(!e.target.closest('.matrix-edit'))select(cell.dataset.id)});
  $('processMatrix').querySelectorAll('.matrix-edit').forEach(input=>input.onchange=()=>{const station=model().processes.find(s=>s.id===input.dataset.id);if(!station)return;snapshot();if(input.classList.contains('matrix-name'))station.name=input.value.trim()||station.name;else if(input.classList.contains('matrix-time'))station.time=Math.max(0,+input.value||0);else{station.mp=Math.max(0,Math.round(+input.value||0));station.auto=station.mp===0}renderAll();scheduleSave();toast('Đã cập nhật bảng layout')});
}
function renderCategories(s){const categories=[...new Set(['DÁN & ÉP',...(model().categories||[]),...model().processes.map(p=>p.category).filter(Boolean)])];$('categoryInput').innerHTML=categories.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('');$('categoryInput').value=s.category}
function renderFlags(s){const tags=[...new Set([...(model().tagCatalog||[]),...model().processes.flatMap(p=>p.tags||[])])];$('flagOptions').innerHTML=tags.map(t=>`<label><input type="checkbox" value="${esc(t)}" ${(s.tags||[]).includes(t)?'checked':''} ${canEdit()?'':'disabled'}><span>${esc(t)}</span></label>`).join('')||'<small>Thêm nhãn để phân loại vị trí theo nhu cầu.</small>'}
function renderStudio(){
  $('lineMeta').value=Number(model().line)||1;$('typeMeta').value=modelType();$('lineMeta').disabled=$('typeMeta').disabled=!canEdit();if($('lobEditLockBtn')){$('lobEditLockBtn').disabled=!canEdit();$('lobEditLockBtn').textContent=lobEditMode?'🔓 Đang cho phép sửa':'🔒 Khóa chỉnh sửa';$('lobEditLockBtn').classList.toggle('active',lobEditMode)}for(const id of ['layoutDataModel','lobDataModel','jigDataModel'])if($(id))$(id).textContent=`${model().name} · ${model().version==='Imported'?'Bản gốc':model().version}`;renderExcelReference();renderLobChart();renderJigInventory();renderSlotControls();renderProcessMatrix();
  const rows=model().processes,objects=physicalObjects(),tableCount=objects.filter(o=>o.kind==='table').length,machineCount=objects.filter(o=>o.kind==='machine'||o.kind==='welder').length;let summary=$('layoutSummary');if(!summary){summary=document.createElement('div');summary.id='layoutSummary';summary.className='layout-summary';$('equipmentDiagram').before(summary)}
  summary.innerHTML=`<b>${rows.length} công đoạn</b><span>${tableCount} bàn trên sơ đồ</span><span>${machineCount} máy / vị trí máy</span><span>${rows.filter(s=>s.auto).length} công đoạn tự động</span><span>${rows.filter(s=>s.critical).length} vị trí trọng điểm</span><span>${rows.filter(s=>stationSkills(s).length).length} vị trí ĐKN</span>`+[...(model().tagCatalog||[])].map(t=>`<span>${esc(t)}: ${rows.filter(s=>(s.tags||[]).includes(t)).length}</span>`).join('');
  $('layoutCapacityNote').textContent='Layout 33 m · Băng tải 27 m · Bàn 0,8 × 0,5 m · Khoảng cách tham chiếu 0,5 m · Kéo thả để đổi vị trí; số công đoạn tự cập nhật theo bố cục, IQC luôn là số 1';
  updateLayoutToolbar();
}
function switchView(view){activeView=view;document.body.dataset.view=view;$('overviewView').hidden=view!=='overview';$('processView').hidden=view!=='processes';$('jigView').hidden=view!=='jigs';document.querySelectorAll('.view-tab').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('printBtn').textContent=view==='jigs'?'In danh sách Jig':view==='processes'?'In LOB':'In layout & setup';if(view==='jigs')renderJigInventory();if(view==='processes')renderLobChart();if(view==='overview')applyLayoutZoom()}
function printCurrentView(layoutMode=layoutVisualMode){
  renderStudio();const m=model(),report=$('printReport'),meta=`<h1>${esc(m.name)} · ${esc(m.version==='Imported'?'Bản gốc':m.version)}</h1><p>Line ${esc(Number(m.line)||1)} · Type ${esc(modelType())} · Layout 33 m · Băng tải 27 m · Bàn 0,8 × 0,5 m</p>`;
  let content=meta;
  if(activeView==='jigs'){content+='<h2>Danh sách Jig & setup</h2>'+$('jigInventorySummary').outerHTML+$('jigInventoryBody').closest('table').outerHTML}
  else if(activeView==='processes'){content+=$('lob-analysis')?.outerHTML||document.querySelector('.lob-analysis').outerHTML;content+=$('processTableBody').closest('table').outerHTML}
  else{
    const objects=physicalObjects(),byStation=new Map();objects.filter(o=>o.station).forEach(o=>{if(!byStation.has(o.station.id))byStation.set(o.station.id,[]);byStation.get(o.station.id).push(o)});
    content+=$('layoutSummary').outerHTML+'<p>V3 = Jig Press · A = Jig Attach · T = Tool · ★ = Trọng điểm · ĐKN = Đa kỹ năng. Số trên sơ đồ đối chiếu bảng setup.</p>'+(layoutMode==='excel'?$('excelLayoutReference').outerHTML:$('equipmentDiagram').innerHTML);
    content+='<h2 class="page-break">Bảng setup công đoạn</h2><table><thead><tr><th>STT</th><th>Công đoạn</th><th>MP</th><th>Thiết bị / vị trí (m)</th><th>ĐKN / trọng điểm</th><th>Jig / setup</th></tr></thead><tbody>'+m.processes.map((s,i)=>`<tr><td>${i+1}</td><td>${esc(s.name)}</td><td>${s.auto?'AUTO · ':''}${s.mp}</td><td>${(byStation.get(s.id)||[]).map(o=>`${{person:'Người',table:'Bàn',machine:'Máy',welder:'Máy hàn',press:'V3',attach:'Attach',tool:'Tool'}[o.kind]}: x ${((o.x-40)/60).toFixed(2)}, y ${((o.y-30)/60).toFixed(2)} · xoay ${o.rotation||0}°`).join('<br>')}</td><td>${s.critical?'★ Trọng điểm<br>':''}${skillLabel(s)}${(s.tags||[]).map(t=>'<br>'+esc(t)).join('')}</td><td>${getJigs(s).map(j=>`${esc(j.name||jigType(j))} (${jigType(j)}) · ${+j.setup?j.setup+' phút':'chưa đo'}`).join('<br>')||'—'}</td></tr>`).join('')+'</tbody></table><p>Tọa độ x/y tính theo mét, gốc tại góc trên trái layout 33 m. Góc xoay và danh sách Jig giúp người vận hành đặt đúng thiết bị khi setup.</p>';
    content+='<h2>Nhân lực</h2>'+$('workforceBody').closest('table').outerHTML;
  }
  report.innerHTML=content;window.print();
}
function openPrintChoice(){if(activeView!=='overview')return printCurrentView();$('printChoiceDialog').showModal()}
async function loadHistory(reset=true){
  if(reset){historyOffset=0;historyRows=[];historyModel=model().name;$('historyList').innerHTML='Đang tải lịch sử…'}
  try{const result=await request('/api/history?model='+encodeURIComponent(historyModel)+'&offset='+historyOffset);historyRows.push(...result.rows);historyOffset+=result.rows.length;$('moreHistoryBtn').hidden=!result.hasMore;$('historyList').innerHTML=historyRows.length?historyRows.map((r,i)=>`<article class="history-item"><b>${esc(r.version)}</b><small>${esc(r.created_at)} UTC · ${esc(r.note||'Tự động lưu')}</small><button class="btn" data-history="${i}">Xem bản lưu</button></article>`).join(''):'Chưa có lịch sử. Lần lưu tiếp theo sẽ được ghi nhận.';$('historyList').querySelectorAll('[data-history]').forEach(b=>b.onclick=()=>previewHistory(historyRows[+b.dataset.history]));}catch(error){$('historyList').textContent=error.message}
}
async function previewHistory(row){const result=await request('/api/history?id='+encodeURIComponent(row.id));const data=result.data;const container=$('historyList');container.innerHTML=`<button id="backHistoryBtn" class="btn">Về danh sách</button><h3>${esc(data.name)} · ${esc(data.version)}</h3><p>${data.processes.length} công đoạn · ${data.processes.flatMap(s=>getJigs(s)).length} Jig</p><p>${esc(data.note||'')}</p><div>${data.processes.map((s,i)=>`<p>${i+1}. ${esc(s.name)} · MP ${s.mp} · ${s.time}s</p>`).join('')}</div>${canEdit()?'<button id="restoreHistoryBtn" class="btn primary">Khôi phục thành phiên bản mới</button>':''}`;$('backHistoryBtn').onclick=()=>loadHistory(true);if(canEdit())$('restoreHistoryBtn').onclick=async()=>{try{await saveCurrent();snapshot();const copy=structuredClone(data);copy.version='Khôi phục '+new Date().toISOString();copy.note='Khôi phục từ '+data.version;currentKey=copy.name+'::'+copy.version;state.models[currentKey]=copy;copy.isLatest=true;await saveCurrent();$('historyDialog').close();renderAll();toast('Đã khôi phục; bản cũ vẫn nằm trong lịch sử')}catch(error){toast(error.message)}}}
function normalizeExcelRow(row){const result={};for(const [key,value] of Object.entries(row||{}))result[norm(key).replace(/[^A-Z0-9]+/g,'_').replace(/^_|_$/g,'')]=value;return result}
function excelRows(){return [...model().processes].sort((a,b)=>(+a.stt||0)-(+b.stt||0))}
function downloadTabWorkbook(kind){
  if(!window.XLSX)throw new Error('Không tải được thư viện Excel.');const rows=excelRows(),book=XLSX.utils.book_new(),safe=String(model().name||'Model').replace(/[\\/?*\[\]:]/g,' ').slice(0,24);
  const data=kind==='layout'?rows.map((s,i)=>({station_no:s.stt||i+1,process_name:s.name,side:s.side||'TOP',slot_index:s.slotIndex||i+1,active:s.isActive!==false?'YES':'NO',tt_seconds:+s.time||0,mp:+s.mp||0,multi_skill:stationSkills(s).join(';'),category:s.category||''})):kind==='lob'?rows.map((s,i)=>({station_no:s.stt||i+1,process_name:s.name,tt_seconds:+s.time||0,mp:+s.mp||0,multi_skill:stationSkills(s).join(';'),category:s.category||''})):rows.flatMap((s,i)=>getJigs(s).map(j=>({station_no:s.stt||i+1,process_name:s.name,jig_type:j.eqType||(jigType(j)==='press'?'V3':jigType(j)==='attach'?'ATTACH':'TEST'),jig_name:j.name||'',setup_minutes:+j.setup||0})));
  const headers=kind==='layout'?['station_no','process_name','side','slot_index','active','tt_seconds','mp','multi_skill','category']:kind==='lob'?['station_no','process_name','tt_seconds','mp','multi_skill','category']:['station_no','process_name','jig_type','jig_name','setup_minutes'];
  const sheet=XLSX.utils.json_to_sheet(data.length?data:[Object.fromEntries(headers.map(h=>[h,'']))],{header:headers});sheet['!cols']=headers.map(h=>({wch:Math.max(14,h.length+2)}));XLSX.utils.book_append_sheet(book,sheet,`${kind==='layout'?'Layout':kind==='lob'?'LOB':'Jig'} ${safe}`.slice(0,31));XLSX.writeFile(book,`${safe}_${kind}_template.xlsx`);toast('Đã tải mẫu Excel '+kind.toUpperCase())
}
function findStationForExcel(draft,row,index){const no=Number(row.STATION_NO||row.STT||row.CONG_DOAN),name=norm(row.PROCESS_NAME||row.TEN_CONG_DOAN);return draft.processes.find(s=>Number(s.stt)===no)||(name&&draft.processes.find(s=>norm(s.name)===name))||draft.processes[index]}
async function commitTabImport(draft,kind){
  const mode=await resolveImportConflict([{parsed:{modelName:draft.name},base:model(),data:draft}]);if(!mode)return toast('Đã hủy nhập Excel.');snapshot();const oldKey=currentKey;
  if(mode==='new'){const stamp=new Date().toISOString().replace(/[-:TZ.]/g,'').slice(0,14);draft.version=`${model().version==='Imported'?'Ver':model().version} · ${kind.toUpperCase()} ${stamp}`;draft.note=`Nhập Excel ${kind.toUpperCase()} · giữ phiên bản cũ`;currentKey=`${draft.name}::${draft.version}`;draft.isLatest=true;state.models[currentKey]=draft}else{draft.version=model().version;draft.note=`Cập nhật Excel ${kind.toUpperCase()} vào phiên bản hiện tại`;draft.isLatest=true;state.models[oldKey]=draft;currentKey=oldKey}
  await saveCurrent(true);renderAll();toast(`Đã nhập Excel ${kind.toUpperCase()} và lưu ${mode==='new'?'phiên bản mới':'phiên bản hiện tại'}`)
}
async function importTabWorkbook(file,kind){
  if(!canEdit())return toast('Bạn không có quyền nhập dữ liệu.');const workbook=XLSX.read(await file.arrayBuffer(),{type:'array'}),sheet=workbook.Sheets[workbook.SheetNames[0]],raw=XLSX.utils.sheet_to_json(sheet,{defval:''}).map(normalizeExcelRow),rows=raw.filter(r=>Object.values(r).some(v=>String(v).trim()));if(!rows.length)throw new Error('File Excel không có dữ liệu.');const draft=structuredClone(model());
  if(kind==='jig'){for(const s of draft.processes)s.jigs=[];for(const [i,row] of rows.entries()){const station=findStationForExcel(draft,row,i);if(!station)continue;const eq=String(row.JIG_TYPE||row.LOAI_JIG||'TEST').trim().toUpperCase(),name=String(row.JIG_NAME||row.MA_TEN_JIG||row.TEN_JIG||'').trim(),setup=Math.max(0,Number(row.SETUP_MINUTES||row.THOI_GIAN_SETUP_PHUT)||0);if(!name&&!setup)continue;station.jigs.push({id:'j-'+Date.now()+'-'+i,name,eqType:['V3','ATTACH','DINO','C_CLIP','C-CLIP','TEST','AUTO'].includes(eq)?eq.replace('C_CLIP','C-CLIP'):'TEST',type:eq==='V3'?'press':eq==='ATTACH'?'attach':'tool',setup})}}
  else for(const [i,row] of rows.entries()){const s=findStationForExcel(draft,row,i),has=key=>Object.prototype.hasOwnProperty.call(row,key)&&row[key]!=='';if(!s)continue;if(row.PROCESS_NAME||row.TEN_CONG_DOAN)s.name=String(row.PROCESS_NAME||row.TEN_CONG_DOAN).trim();if(has('TT_SECONDS')||has('T_T_GIAY'))s.time=Math.max(0,Number(row.TT_SECONDS||row.T_T_GIAY)||0);if(has('MP')){s.mp=Math.max(0,Math.round(Number(row.MP)||0));s.auto=s.mp===0}if(row.CATEGORY||row.DANH_MUC)s.category=String(row.CATEGORY||row.DANH_MUC).trim();const skills=String(row.MULTI_SKILL||row.DA_KY_NANG||'').split(/[;,]/).map(v=>Number(v.replace('%','').trim())).filter(v=>Number.isInteger(v)&&v>0&&v<=100);if(skills.length){s.multiSkills=[...new Set(skills)];s.skill25=skills.includes(25);s.skill40=skills.includes(40)}if(kind==='layout'){const side=String(row.SIDE||row.NHANH||'').toUpperCase();if(['TOP','BOTTOM','HEAD'].includes(side))s.side=side;if(has('SLOT_INDEX'))s.slotIndex=Math.max(1,Math.min(27,Math.round(Number(row.SLOT_INDEX)||1)));if(has('ACTIVE'))s.isActive=!['NO','FALSE','0','OFF','TAT'].includes(norm(row.ACTIVE))}}
  await commitTabImport(draft,kind)
}
function wireTabExcel(kind){const cap=kind[0].toUpperCase()+kind.slice(1),template=$(kind+'XlsxTemplateBtn'),importButton=$(kind+'XlsxImportBtn'),file=$(kind+'XlsxFile'),save=$(kind+'SaveBtn');template.onclick=()=>{try{downloadTabWorkbook(kind)}catch(error){toast(error.message)}};importButton.onclick=()=>file.click();file.onchange=async()=>{const selected=file.files[0];file.value='';if(!selected)return;try{await importTabWorkbook(selected,kind)}catch(error){toast(error.message)}};save.onclick=async()=>{try{await saveCurrent(true);toast(`Đã lưu dữ liệu ${cap} của ${model().name}`)}catch(error){toast(error.message)}}}
function initStudio(){
  $('layoutZoom').onchange=applyLayoutZoom;$('printJigsBtn').onclick=()=>{switchView('jigs');printCurrentView()};
  $('lobEditLockBtn').onclick=()=>{if(!canEdit())return;lobEditMode=!lobEditMode;renderProcessTable();renderStudio();toast(lobEditMode?'Đã mở khóa chỉnh sửa LOB':'Đã khóa chỉnh sửa LOB')};$('printExcelVersionBtn').onclick=()=>{$('printChoiceDialog').close();printCurrentView('excel')};$('printConvertedVersionBtn').onclick=()=>{$('printChoiceDialog').close();printCurrentView('interactive')};$('cancelPrintChoiceBtn').onclick=()=>$('printChoiceDialog').close();
  $('excelLayoutModeBtn').onclick=()=>setLayoutVisualMode('excel');$('interactiveLayoutModeBtn').onclick=()=>setLayoutVisualMode('interactive');$('replaceReferenceBtn').onclick=()=>$('referenceImageFile').click();$('referenceImageFile').onchange=e=>{const file=e.target.files[0];e.target.value='';importReferenceImage(file)};
  $('addInventoryJigBtn').onclick=()=>{if(!canEdit())return;const station=model().processes.find(s=>s.id===$('jigStationSelect').value);if(!station)return;snapshot();station.jigs=getJigs(station);station.jigs.push({id:'j'+Date.now(),name:'',type:'attach',eqType:'ATTACH',setup:0});renderAll();scheduleSave();toast('Đã thêm Jig cho '+station.name)};
  $('workforceToggle').onclick=()=>{const open=$('workforcePanel').classList.toggle('expanded');$('workforceToggle').textContent=open?'Thu gọn nhân lực':'Xem chi tiết nhân lực';$('workforceToggle').setAttribute('aria-expanded',String(open))};
  $('layoutLockBtn').onclick=()=>{layoutEditMode=!layoutEditMode;renderEquipmentDiagram();toast(layoutEditMode?'Đã bật chỉnh sửa bố cục':'Đã khóa bố cục')};$('rotateObjectBtn').onclick=rotateSelectedObject;$('copyObjectBtn').onclick=copySelectedObject;$('pasteObjectBtn').onclick=pasteLayoutObject;$('duplicateObjectBtn').onclick=duplicateSelectedObject;$('snapObjectBtn').onclick=snapSelectedObject;$('deleteObjectBtn').onclick=deleteSelectedObject;
  $('saveMetaBtn').onclick=()=>{if(!canEdit())return;const line=Number($('lineMeta').value);if(!Number.isInteger(line)||line<1)return toast('Line phải là số nguyên từ 1.');snapshot();model().line=line;model().type=$('typeMeta').value;renderAll();scheduleSave()};
  $('addCategoryBtn').onclick=()=>{if(!canEdit())return;const name=window.prompt('Tên danh mục công đoạn mới:')?.trim();if(!name)return;snapshot();model().categories=[...new Set([...(model().categories||[]),name])];const s=model().processes.find(s=>s.id===selectedId);s.category=name;renderCategories(s);scheduleSave()};
  $('addFlagBtn').onclick=()=>{if(!canEdit())return;const name=window.prompt('Tên nhãn vị trí mới:')?.trim();if(!name)return;snapshot();model().tagCatalog=[...new Set([...(model().tagCatalog||[]),name])];const s=model().processes.find(s=>s.id===selectedId);s.tags=[...new Set([...(s.tags||[]),name])];renderFlags(s);renderStudio();scheduleSave()};
  $('historyBtn').onclick=()=>{$('historyDialog').showModal();loadHistory(true)};$('closeHistoryBtn').onclick=()=>$('historyDialog').close();$('moreHistoryBtn').onclick=()=>loadHistory(false);
  for(const kind of ['layout','lob','jig'])wireTabExcel(kind);
  window.addEventListener('resize',()=>{if($('layoutZoom').value==='fit')applyLayoutZoom()});
}
function layoutPositions(rows){
  const positions=new Map(),occupied=[];
  for(const s of rows){let x=Math.max(0,Number(s.x)||0),y=Math.max(40,Number(s.y)||60);
    while(occupied.some(p=>Math.abs(p.x-x)<78&&Math.abs(p.y-y)<90))x+=78;
    const point={x,y};positions.set(s.id,point);occupied.push(point);
  }
  return positions;
}
function renderLobChart(){
  const rows=model().processes,m=metrics(),measured=rows.filter(s=>Number(s.time)>0),missing=rows.length-measured.length;
  $('chartModel').textContent=model().name;
  $('chartDataNote').textContent=missing?`${missing}/${rows.length} công đoạn chưa có T/T. Chỉ số hiện tại là tạm tính; màu xám: chưa đo.`:'T/T theo số thứ tự công đoạn · Đỏ: neck time · Xanh: các công đoạn còn lại.';
  const available=Math.max(860,window.innerWidth-320),step=Math.max(27,Math.min(52,(available-90)/Math.max(1,rows.length))),w=Math.max(780,rows.length*step+80),h=292,left=48,top=26,bottom=246,range=Math.max(1,Math.ceil(Math.max(m.neck,...rows.map(s=>+s.time||0))*1.12)),barWidth=Math.max(17,Math.min(30,step-12));
  let parts=[];
  for(let i=0;i<=4;i++){const value=range*i/4,y=bottom-(bottom-top)*i/4;parts.push(`<line x1="${left}" x2="${w-12}" y1="${y}" y2="${y}" stroke="#dce5e8"/><text x="${left-8}" y="${y+4}" text-anchor="end" fill="#6c8089" font-size="11">${value.toFixed(1)}</text>`)}
  if(m.neck){const neckY=bottom-(bottom-top)*m.neck/range;parts.push(`<line x1="${left}" x2="${w-12}" y1="${neckY}" y2="${neckY}" stroke="#e9342b" stroke-width="2" stroke-dasharray="8 6"/><text x="${w-16}" y="${neckY-6}" text-anchor="end" fill="#c72e25" font-size="10" font-weight="bold">NECK ${m.neck.toFixed(2)}s</text>`)}
  rows.forEach((s,i)=>{const time=Math.max(0,+s.time||0),bh=(bottom-top)*time/range,x=left+14+i*step,y=bottom-bh,isNeck=m.neck>0&&Math.abs(stationCycle(s)-m.neck)<.005;
    parts.push(`<g class="lob-bar" data-id="${esc(s.id)}" tabindex="0" role="button" aria-label="${esc((i+1)+'. '+s.name+': '+(time?time+' giây':'chưa có T/T'))}"><title>${esc(s.name)} · ${time?time.toFixed(2)+' giây':'Chưa có T/T'}</title><rect x="${x-5}" y="${top}" width="${step-4}" height="${bottom-top+30}" fill="transparent"/><rect x="${x}" y="${time?y:bottom-3}" width="${barWidth}" height="${time?bh:3}" fill="${!time?'#b1bfc4':isNeck?'#ed352d':'#1b6986'}"/><text x="${x+barWidth/2}" y="${time?y-6:bottom-8}" text-anchor="middle" fill="#34505b" font-size="10">${time?time.toFixed(2):'—'}</text><text x="${x+barWidth/2}" y="${bottom+19}" text-anchor="middle" font-size="11">${i+1}</text></g>`);
  });
  $('lobChart').innerHTML=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${w} ${h}" width="${w}" height="${h}" preserveAspectRatio="xMidYMid meet" role="img" aria-label="Biểu đồ thời gian công đoạn từ 1 đến ${rows.length}"><text x="8" y="15" font-size="11">Giây</text>${parts.join('')}</svg>`;
  const avg=rows.length?m.sum/rows.length:0,min=measured.length?Math.min(...measured.map(s=>+s.time)):0;
  const stats=[['Model',model().name],['LOB',measured.length?(m.lob*100).toFixed(1)+'%':'—'],['Tổng thời gian',measured.length?m.sum.toFixed(2)+' s':'—'],['Công đoạn',rows.length],['Neck time',m.neck?m.neck.toFixed(2)+' s':'—'],['Trung bình',measured.length?avg.toFixed(2)+' s':'—'],['T/T nhỏ nhất đã đo',min?min.toFixed(2)+' s':'—'],['UPH',m.uph?m.uph.toFixed(0):'—'],['MP',m.mp]];
  $('lobStats').innerHTML=stats.map(([label,value])=>`<article><span>${label}</span><strong>${esc(value)}</strong></article>`).join('');
  $('lobChart').querySelectorAll('.lob-bar').forEach(el=>{const activate=()=>{selectedId=el.dataset.id;renderProcessTable();const row=[...$('processTableBody').querySelectorAll('tr')].find(r=>r.dataset.id===selectedId);row?.classList.add('chart-selected');row?.scrollIntoView({block:'nearest',behavior:'smooth'})};el.onclick=activate;el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();activate()}}});
}

