import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const read=name=>fs.readFileSync(new URL('../'+name,import.meta.url),'utf8');
const app=read('app.js'),office=read('office-page-editor.js'),mobile=read('mobile-ux.js');
const section=(source,start,end)=>source.slice(source.indexOf(start),source.indexOf(end,source.indexOf(start)));
function element(){const classes=new Set();return{children:[],attributes:{},value:'',textContent:'',open:false,classList:{toggle(name,on){on=on??!classes.has(name);on?classes.add(name):classes.delete(name);return on},contains:name=>classes.has(name)},setAttribute(name,value){this.attributes[name]=value},appendChild(child){this.children.push(child)},replaceChildren(){this.children=[]},focus(){this.focused=true},addEventListener(){},showModal(){this.open=true},close(){this.open=false},after(){},querySelector(){return this.children[0]},get childElementCount(){return this.children.length}}}
function picker(){
 const nodes={modelSelect:element(),modelPickerSearch:element(),modelPickerResults:element(),modelPickerCount:element()};
 const select=nodes.modelSelect;select.options=[{value:'s948',textContent:'S948',selected:true},{value:'b3',textContent:'S947 Block 3'},{value:'vn',textContent:'Dây chuyền Đặc biệt'}];select.selectedOptions=[select.options[0]];
 const calls=[];select.onchange=async event=>{calls.push(event.target.value);select.selectedOptions=[select.options.find(option=>option.value===event.target.value)]};
 const created=[];const context={$:id=>nodes[id],renderModels(){},document:{createElement(){const e=element();Object.defineProperty(e,'id',{set(id){nodes[id]=e},get(){return Object.keys(nodes).find(id=>nodes[id]===e)}});created.push(e);if(created.length===2)e.children.push(element());return e},body:{appendChild(){}}}};
 vm.createContext(context);vm.runInContext(app.slice(app.indexOf('/* Search the existing model options;')),context);
 return{nodes,select,calls,context};
}
test('model search filters case and Vietnamese accents without removing original options',()=>{const p=picker();p.nodes.modelPickerButton.onclick();p.nodes.modelPickerSearch.value='day chuyen dac';p.nodes.modelPickerSearch.oninput();assert.deepEqual(p.nodes.modelPickerResults.children.map(e=>e.textContent),['Dây chuyền Đặc biệt']);assert.equal(p.select.options.length,3)});
test('model search empty results do not change the current selection',()=>{const p=picker();p.nodes.modelPickerButton.onclick();p.nodes.modelPickerSearch.value='unknown';p.nodes.modelPickerSearch.oninput();assert.equal(p.nodes.modelPickerResults.children.length,0);assert.equal(p.select.selectedOptions[0].value,'s948');assert.equal(p.nodes.modelPickerCount.textContent,'Không tìm thấy model.')});
test('selecting a filtered model uses the existing save and permission handler',async()=>{const p=picker();p.nodes.modelPickerButton.onclick();p.nodes.modelPickerSearch.value='BLOCK 3';p.nodes.modelPickerSearch.oninput();await p.nodes.modelPickerResults.children[0].onclick();assert.deepEqual(p.calls,['b3']);assert.equal(p.nodes.modelPickerButton.textContent,'S947 Block 3');assert.equal(p.nodes.modelPickerDialog.open,false)});
test('model picker follows dynamically refreshed options and permitted create action',()=>{const p=picker();p.nodes.modelPickerButton.onclick();p.select.options.push({value:'__add_model__',textContent:'Thêm Model mới'});p.context.renderModels();assert.equal(p.nodes.modelPickerResults.children.length,4);p.select.options.pop();p.context.renderModels();assert.equal(p.nodes.modelPickerResults.children.length,3)});
test('mobile fullscreen toggles exit label and releases the page scroll lock',()=>{const zone=element(),button=element(),body=element(),context={document:{body,querySelector:selector=>selector==='.shapes-zone'?zone:button},scheduleViewportUpdate(){}};vm.createContext(context);vm.runInContext(section(mobile,'function setMobileFullscreen(',"\n document.addEventListener('keydown'"),context);context.setMobileFullscreen(true);assert.equal(button.textContent,'Thoát toàn màn hình');assert.ok(body.classList.contains('mobile-layout-expanded'));context.setMobileFullscreen(false);assert.equal(button.attributes['aria-pressed'],'false');assert.equal(body.classList.contains('mobile-layout-expanded'),false)});
test('worksheet pan reaches objects outside print area without altering that area',()=>{const canvas={widthMeters:33,heightMeters:8,pixelsPerMeter:100},context={layoutEditing:true,odoc:()=>({canvas}),fabricLayoutCanvas:{width:1000,height:600,viewportTransform:[1,0,0,1,0,0],getObjects:()=>[{layoutId:'outside',getBoundingRect:()=>({left:7000,top:-1200,width:100,height:100})}]}};vm.createContext(context);vm.runInContext(section(office,'function officePanBounds(', 'function syncOfficePanControls('),context);const bounds=context.officePanBounds();assert.ok(bounds.xMin<=1000-7100);assert.ok(bounds.yMax>=1200);assert.deepEqual(canvas,{widthMeters:33,heightMeters:8,pixelsPerMeter:100});context.layoutEditing=false;assert.equal(context.officePanBounds().xMax,42)});
for(const fail of [false,true])test(`print uses configured region and restores worksheet state (${fail?'failure':'success'})`,()=>{
 const page={name:'office-page',fill:'transparent',stroke:'green',strokeDashArray:[10,6],shadow:null,excludeFromExport:true,set(values){Object.assign(this,values)}},active={},original=[.5,0,0,.5,40,80];let captured;
 const fabric={viewportTransform:[...original],backgroundColor:'transparent',getActiveObject:()=>active,getObjects:()=>[page],discardActiveObject(){},setActiveObject(value){this.active=value},setViewportTransform(value){this.viewportTransform=value},requestRenderAll(){},toDataURL(options){captured=options;assert.equal(page.stroke,'transparent');assert.equal(page.fill,'#fefefe');if(fail)throw new Error('export failed');return'data:image/png;base64,test'}};
 const context={odoc:()=>({canvas:{widthMeters:33,heightMeters:8,pixelsPerMeter:100,background:'#fefefe'}}),fabricLayoutCanvas:fabric};vm.createContext(context);vm.runInContext(section(office,'function phase2dLayoutImage(', '\nprintOffice=function'),context);
 if(fail)assert.throws(()=>context.phase2dLayoutImage(),/export failed/);else assert.match(context.phase2dLayoutImage(),/^data:image/);
 assert.equal(captured.width,3300);assert.equal(captured.height,800);assert.equal(captured.left,0);assert.equal(page.fill,'transparent');assert.equal(page.stroke,'green');assert.equal(fabric.backgroundColor,'transparent');assert.deepEqual([...fabric.viewportTransform],original);assert.equal(fabric.active,active);
});
