(function(root){
 const STORAGE_KEY='ist-lob-language';
 const messages={
  vi:{model:'Model',version:'Phiên bản',viewer:'Chỉ xem',edit:'Chỉnh sửa',management:'Quản lý',account:'Tài khoản',login:'Đăng nhập',editLayout:'Sửa Layout',editLob:'Sửa LOB',editEquipment:'Sửa Thiết bị & Jig',measureTt:'Đo T/T',modelVersion:'Model & Version',createVersion:'Tạo Version',publish:'Publish',historyRestore:'Lịch sử / Khôi phục',permissions:'Phân quyền',excelImport:'Nhập Excel',backup:'Sao lưu dữ liệu',restoreBackup:'Khôi phục backup',cancel:'Hủy',save:'Lưu',renameModel:'Đổi tên Model',deleteModel:'Xóa Model',renameVersion:'Đổi tên Version',deleteVersion:'Xóa Version',viewOriginalExcel:'▣ Xem Excel gốc',printTitle:'Chọn bản cần in',printHelp:'Bản Excel giữ nguyên tài liệu gốc. Bản đã chỉnh sửa sử dụng layout hiện tại trên webapp.',printOriginal:'In bản Excel gốc',printOriginalHelp:'Giữ nguyên mẫu trong file Excel',printEdited:'In bản đã chỉnh sửa',printEditedHelp:'Layout convert hiện tại của webapp',publicViewer:'Viewer công khai',readOnly:'Chỉ xem',saved:'Đã lưu'},
  en:{model:'Model',version:'Version',viewer:'Viewer',edit:'Edit',management:'Management',account:'Account',login:'Sign in',editLayout:'Edit Layout',editLob:'Edit LOB',editEquipment:'Edit Equipment & Jig',measureTt:'Measure T/T',modelVersion:'Model & Version',createVersion:'Create Version',publish:'Publish',historyRestore:'History / Restore',permissions:'Permissions',excelImport:'Excel Import',backup:'Backup Data',restoreBackup:'Restore Backup',cancel:'Cancel',save:'Save',renameModel:'Rename Model',deleteModel:'Delete Model',renameVersion:'Rename Version',deleteVersion:'Delete Version',viewOriginalExcel:'▣ View Original Excel',printTitle:'Choose a layout to print',printHelp:'Original Excel preserves the source document. Edited Layout prints the current web layout.',printOriginal:'Print Original Excel',printOriginalHelp:'Preserve the original Excel layout',printEdited:'Print Edited Layout',printEditedHelp:'Print the current converted web layout',publicViewer:'Public Viewer',readOnly:'Read only',saved:'Saved'}
 };
 let language=localStorage.getItem(STORAGE_KEY)==='en'?'en':'vi';
 const t=key=>messages[language]?.[key]||messages.vi[key]||key;
 function apply(scope=document){scope.querySelectorAll('[data-i18n]').forEach(element=>{element.textContent=t(element.dataset.i18n)});document.documentElement.lang=language;document.dispatchEvent(new CustomEvent('ist-language-change',{detail:{language}}))}
 function setLanguage(next){language=next==='en'?'en':'vi';localStorage.setItem(STORAGE_KEY,language);apply();return language}
 root.ISTI18n={t,apply,setLanguage,get language(){return language},messages};
})(globalThis);
